name: Build SokoMaster Installer (Nuitka + Inno Setup)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permet de lancer la compilation manuellement depuis GitHub

jobs:
  # ==========================================
  # JOB UNIQUE : COMPILATION NUITKA & INSTALLATEUR
  # ==========================================
  build-installer:
    runs-on: windows-latest

    steps:
    - name: 📥 Cloner le dépôt
      uses: actions/checkout@v4

    - name: 🐍 Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 📦 Installer les dépendances Python
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter cryptography httpx nuitka fpdf

    - name: 🔨 Compiler avec Nuitka (Mode Standalone)
      run: |
        python -m nuitka --standalone --windows-console-mode=attach --enable-plugin=tk-inter --company-name="CRYPT Enterprise" --windows-icon-from-ico=icon.ico --product-name="SokoMaster" --file-version=1.0.0.0 --product-version=1.0.0.0 --assume-yes-for-downloads --output-dir="dist" main.py

    - name: 🛠️ Installer Inno Setup
      run: |
        choco install innosetup -y

    - name: 📦 Générer l'Installeur SokoMaster (.exe)
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup_script.iss
      shell: powershell

    - name: 🚀 Uploader l'installeur final SokoMaster
      uses: actions/upload-artifact@v4
      with:
        name: SokoMaster-Setup-Windows
        path: Output/SokoMaster_Setup_v1.0.exe
